package com.example.trinetraai.presetData

object ActCategoryMap {

    val actCategoryMap: Map<String, String> = mapOf(
        "Theft" to "IPC",
        "Assault" to "IPC",
        "Burglary" to "IPC",
        "Cyber Crime" to "Information Technology (IT) Act, 2000",
        "Robbery" to "IPC",
        "Murder" to "IPC",
        "Drug Possession" to "Narcotic Drugs and Psychotropic Substances (NDPS) Act, 1985",
        "Vandalism" to "IPC",
        "Fraud" to "IPC",
        "Housebreaking" to "IPC",
        "Kidnapping" to "IPC",
        "Dowry Death" to "IPC",
        "Rape" to "IPC",
        "Attempt to Murder" to "IPC",
        "Domestic Violence" to "Protection of Women from Domestic Violence (PWDV) Act, 2005 & IPC",
        "Child Abuse" to "Protection of Children from Sexual Offences (POCSO) Act, 2012 & IPC & Juvenile Justice (Care and Protection of Children) Act, 2015",
        "Human Trafficking" to "IPC & Immoral Traffic (Prevention) Act (ITPA), 1956",
        "Rioting" to "IPC",
        "Bribery" to "Prevention of Corruption Act, 1988",
        "Extortion" to "IPC",
        "Acid Attack" to "IPC",
        "ShopLifting" to "IPC",
        "Drunk Driving" to "Motor Vehicles Act, 1988",
        "Arson" to "IPC",
        "Terrorism" to "Unlawful Activities (Prevention) Act (UAPA), 1967",
        "Cheating" to "IPC",
        "Stalking" to "IPC",
        "Money Laundering" to "Prevention of Money Laundering Act (PMLA), 2002",
        "Hate Speech" to "IPC",
        "Obscenity" to "IPC",
        "Attempt to Suicide" to "IPC",
        "Sexual Harassment" to "IPC & Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013",
        "Online Harassment" to "Information Technology (IT) Act, 2000 & IPC",
        "Honour Killing" to "IPC",
        "Female Infanticide" to "IPC",
        "Child Marriage" to "Prohibition of Child Marriage Act, 2006",
        "Workplace Harassment" to "Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 & IPC",
        "Cyber Stalking" to "Information Technology (IT) Act, 2000 & IPC",
        "Voyeurism" to "IPC",
        "Public Indecency" to "IPC",
        "Unlawful Assembly" to "IPC",
        "Embezzlement" to "IPC",
        "Counterfeiting" to "IPC",
        "Identity Theft" to "Information Technology (IT) Act, 2000 & IPC",
        "Drug Trafficking" to "Narcotic Drugs and Psychotropic Substances (NDPS) Act, 1985",
        "Arms Trafficking" to "Arms Act, 1959",
        "Smuggling" to "Customs Act, 1962 & IPC",
        "Perjury" to "IPC",
        "Tax Evasion" to "Income Tax Act, 1961 & Goods and Services Tax (GST) Acts & IPC (for related fraud)",
        "Insider Trading" to "Securities and Exchange Board of India (SEBI) Act, 1992",
        "Environmental Crime" to "Environment (Protection) Act, 1986 & Water (Prevention and Control of Pollution) Act, 1974 & Air (Prevention and Control of Pollution) Act, 1981 & IPC",
        "Wildlife Poaching" to "Wildlife Protection Act, 1972",
        "Cyber Espionage" to "Information Technology (IT) Act, 2000 & IPC",
        "Grievous Hurt" to "IPC",
        "Criminal Intimidation" to "IPC",
        "Abduction" to "IPC",
        "Culpable Homicide Not Amounting to Murder" to "IPC",
        "Voluntarily Causing Hurt" to "IPC",
        "Wrongful Restraint" to "IPC",
        "Wrongful Confinement" to "IPC",
        "Criminal Force" to "IPC",
        "Mischief" to "IPC",
        "Criminal Trespass" to "IPC",
        "Dacoity" to "IPC",
        "Criminal Breach of Trust" to "IPC",
        "Criminal Misappropriation of Property" to "IPC",
        "Receiving Stolen Property" to "IPC",
        "Falsification of Accounts" to "IPC",
        "Forgery" to "IPC",
        "Illegal Gambling" to "Public Gambling Act, 1867",
        "Public Nuisance" to "IPC",
        "Affray" to "IPC",
        "Sedition" to "IPC",
        "Contempt of Court" to "Contempt of Courts Act, 1971",
        "Resisting Arrest" to "IPC",
        "Escaping Lawful Custody" to "IPC",
        "Harbouring an Offender" to "IPC",
        "Criminal Conspiracy" to "IPC",
        "Racketeering" to "MCOCA & IPC",
        "Organized Crime" to "MCOCA & IPC",
        "Piracy (Copyright/Intellectual Property)" to "Copyright Act, 1957 & Trademarks Act, 1999",
        "Black Marketing" to "Essential Commodities Act, 1955 & IPC",
        "Adulteration of Food or Drugs" to "IPC & Food Safety and Standards Act, 2006 & Drugs and Cosmetics Act, 1940",
        "Medical Negligence (Criminal)" to "IPC",
        "Cruelty to Animals" to "Prevention of Cruelty to Animals Act, 1960 & IPC",
        "Illegal Mining" to "Mines and Minerals (Development and Regulation) Act, 1957 & IPC",
        "Illegal Sand Dredging" to "State Specific Mining Rules & IPC",
        "Violation of Environmental Laws" to "Environment (Protection) Act, 1986",
        "Illegal Possession of Weapons" to "Arms Act, 1959",
        "Explosives Act Violations" to "Explosives Act, 1884 & Explosive Substances Act, 1908",
        "Corruption (Broader than just bribery)" to "Prevention of Corruption Act, 1988",
        "Accepting Illegal Gratuities" to "Prevention of Corruption Act, 1988",
        "Obstruction of Justice" to "IPC",
        "Witness Tampering" to "IPC",
        "Filing False Information to Police" to "IPC",
        "Disobedience to Order Duly Promulgated by Public Servant" to "IPC",
        "Selling Obscene Material" to "IPC",
        "Bigamy" to "IPC",
        "Defamation" to "IPC",
        "Criminal Breach of Contract" to "IPC",
        "Cyber Terrorism" to "Information Technology (IT) Act, 2000",
        "Supply Chain Fraud" to "IPC",
        "Insurance Fraud" to "IPC",
        "Bank Fraud" to "IPC & Prevention of Money Laundering Act (PMLA), 2002",
        "Credit Card Fraud" to "IPC & Information Technology (IT) Act, 2000",
        "Securities Fraud" to "Securities and Exchange Board of India (SEBI) Act, 1992 & IPC",
        "Ponzi Scheme" to "Banning of Unregulated Deposit Schemes Act, 2019 & IPC",
        "Human Organ Trafficking" to "Transplantation of Human Organs and Tissues Act, 1994 & IPC",
        "Kidnapping for Ransom" to "IPC",
        "Armed Robbery" to "IPC",
        "Carjacking" to "IPC",
        "Assault on Public Servant" to "IPC",
        "Waging War Against the State" to "IPC",
        "Incitement to Riot" to "IPC",
        "Unlawful Manufacturing of Drugs" to "NDPS Act, 1985",
        "Possession of Illegal Firearms" to "Arms Act, 1959",
        "Mugging" to "IPC",
        "Shoplifting" to "IPC",
        "Vagrancy (where criminalized)" to "Local Police Acts / State Laws",
        "Smuggling of Antiquities" to "Antiquities and Art Treasures Act, 1972 & Customs Act, 1962 & IPC",
        "Passport Fraud" to "Passport Act, 1967 & IPC",
        "Visa Fraud" to "Foreigners Act, 1946 & IPC",
        "Online Impersonation (non-harassment related)" to "Information Technology (IT) Act, 2000 & IPC",
        "Phishing (General financial fraud)" to "Information Technology (IT) Act, 2000 & IPC",
        "DDoS Attack" to "Information Technology (IT) Act, 2000",
        "Child Labour (Violation of laws)" to "Child Labour (Prohibition and Regulation) Act, 1986 & IPC",
        "Bonded Labour" to "Bonded Labour System (Abolition) Act, 1976 & IPC",
        "Illegal Construction" to "Municipal/State Town Planning Acts & IPC",
        "Violation of Building Codes" to "Municipal/State Town Planning Acts",
        "Selling Adulterated Products" to "IPC & Food Safety and Standards Act, 2006 & Drugs and Cosmetics Act, 1940",
        "Exploitation of Labour" to "IPC & Labour Laws",
        "Endangering Life or Personal Safety of Others" to "IPC",
        "Spreading Disease Malignantly" to "IPC"
    )
}
