package com.example.trinetraai.presetData

object ReportingPS {

    val reportingStationMap = mapOf(
        "North Campus - Zone 1" to "North Campus PS",
        "Murthal (Nearby) - Zone 2" to "Murthal PS",
        "Rohini - Zone 3" to "Rohini PS",
        "Rajouri Garden - Zone 4" to "Rajouri Garden PS",
        "Karol Bagh - Zone 5" to "Karol Bagh PS",
        "South West Delhi - Zone 6" to "South West Delhi PS",
        "HKV (Hauz Khas) - Zone 7" to "Hauz Khas PS",
        "Gurgaon - Zone 8" to "Gurgaon PS",
        "Saket - Zone 9" to "Saket PS",
        "Random Sarai - Zone 10" to "Random Sarai PS",
        "Chhatarpur Farms - Zone 11" to "Chhatarpur PS",
        "Okhla - Zone 12" to "Okhla PS",
        "CR Park (Kalkaji) - Zone 13" to "CR Park PS",
        "Nehru Place - Zone 14" to "Nehru Place PS",
        "GK (Greater Kailash) - Zone 15" to "Greater Kailash PS",
        "Khan Market - Zone 16" to "Khan Market PS",
        "Sarojini Nagar - Zone 17" to "Sarojini Nagar PS",
        "CP (Connaught Place) - Zone 18" to "Connaught Place PS",
        "Palika Bazaar - Zone 19" to "Palika Bazaar PS",
        "Jantar Mantar - Zone 20" to "Jantar Mantar PS",
        "India Gate - Zone 21" to "India Gate PS",
        "Chandni Chowk - Zone 22" to "Chandni Chowk PS",
        "Laxmi Nagar - Zone 23" to "Laxmi Nagar PS",
        "Shahdara - Zone 24" to "Shahdara PS",
        "Noida - Zone 25" to "Noida PS",
        "Yamuna Vihar - Zone 26" to "Yamuna Vihar PS",
        "Pitampura - Zone 27" to "Pitampura PS",
        "Dwarka - Zone 28" to "Dwarka PS",
        "Janakpuri - Zone 29" to "Janakpuri PS",
        "Lajpat Nagar - Zone 30" to "Lajpat Nagar PS",
        "Daryaganj - Zone 31" to "Daryaganj PS",
        "Pusa Road - Zone 32" to "Pusa Road PS",
        "Mandi House - Zone 33" to "Mandi House PS",
        "Lodhi Garden - Zone 34" to "Lodhi Garden PS",
        "Defence Colony - Zone 35" to "Defence Colony PS",
        "Green Park - Zone 36" to "Green Park PS",
        "Vasant Kunj - Zone 37" to "Vasant Kunj PS",
        "Malviya Nagar - Zone 38" to "Malviya Nagar PS",
        "Greater Kailash 2 - Zone 39" to "Greater Kailash 2 PS",
        "Vasant Vihar - Zone 40" to "Vasant Vihar PS",
        "Preet Vihar - Zone 41" to "Preet Vihar PS",
        "Anand Vihar - Zone 42" to "Anand Vihar PS",
        "Mayur Vihar - Zone 43" to "Mayur Vihar PS",
        "Dilshad Garden - Zone 44" to "Dilshad Garden PS",
        "Punjabi Bagh - Zone 45" to "Punjabi Bagh PS",
        "Tilak Nagar - Zone 46" to "Tilak Nagar PS",
        "Uttam Nagar - Zone 47" to "Uttam Nagar PS",
        "Civil Lines - Zone 48" to "Civil Lines PS",
        "Model Town - Zone 49" to "Model Town PS",
        "Seelampur - Zone 50" to "Seelampur PS",
        "Mustafabad - Zone 51" to "Mustafabad PS",
        "Shalimar Bagh - Zone 52" to "Shalimar Bagh PS",
        "Paschim Vihar - Zone 53" to "Paschim Vihar PS",
        "Jasola - Zone 54" to "Jasola PS",
        "Badarpur - Zone 55" to "Badarpur PS",
        "Ghaziabad - Zone 56" to "Ghaziabad PS",
        "Faridabad - Zone 57" to "Faridabad PS",
        "Sonepat - Zone 58" to "Sonepat PS",
        "Indirapuram - Zone 59" to "Indirapuram PS",
        "Palam Colony - Zone 60" to "Palam Colony PS"
    )
}