package com.example.trinetraai.presetData

object ZoneData {
    val zoneList = arrayOf(
        "North Campus - Zone 1",
        "Murthal (Nearby) - Zone 2",
        "Rohini - Zone 3",
        "Rajouri Garden - Zone 4",
        "Karol Bagh - Zone 5",
        "South West Delhi - Zone 6",
        "HKV (Hauz Khas) - Zone 7",
        "Gurgaon - Zone 8",
        "Saket - Zone 9",
        "Random Sarai - Zone 10",
        "Chhatarpur Farms - Zone 11",
        "Okhla - Zone 12",
        "CR Park (Kalkaji) - Zone 13",
        "Nehru Place - Zone 14",
        "GK (Greater Kailash) - Zone 15",
        "Khan Market - Zone 16",
        "Sarojini Nagar - Zone 17",
        "CP (Connaught Place) - Zone 18",
        "Palika Bazaar - Zone 19",
        "Jantar Mantar - Zone 20",
        "India Gate - Zone 21",
        "Chandni Chowk - Zone 22",
        "Laxmi Nagar - Zone 23",
        "Shahdara - Zone 24",
        "Noida - Zone 25",
        "Yamuna Vihar - Zone 26",
        "Pitampura - Zone 27",
        "Dwarka - Zone 28",
        "Janakpuri - Zone 29",
        "Lajpat Nagar - Zone 30",
        "Daryaganj - Zone 31",
        "Pusa Road - Zone 32",
        "Mandi House - Zone 33",
        "Lodhi Garden - Zone 34",
        "Defence Colony - Zone 35",
        "Green Park - Zone 36",
        "Vasant Kunj - Zone 37",
        "Malviya Nagar - Zone 38",
        "Greater Kailash 2 - Zone 39",
        "Vasant Vihar - Zone 40",
        "Preet Vihar - Zone 41",
        "Anand Vihar - Zone 42",
        "Mayur Vihar - Zone 43",
        "Dilshad Garden - Zone 44",
        "Punjabi Bagh - Zone 45",
        "Tilak Nagar - Zone 46",
        "Uttam Nagar - Zone 47",
        "Civil Lines - Zone 48",
        "Model Town - Zone 49",
        "Seelampur - Zone 50",
        "Mustafabad - Zone 51",
        "Shalimar Bagh - Zone 52",
        "Paschim Vihar - Zone 53",
        "Jasola - Zone 54",
        "Badarpur - Zone 55",
        "Ghaziabad - Zone 56",
        "Faridabad - Zone 57",
        "Sonepat - Zone 58",
        "Indirapuram - Zone 59",
        "Palam Colony - Zone 60"
    )

}