services:
  - type: web
    name: trinetra-api 
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app 
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
